# Generated by Django 5.1 on 2024-09-16 18:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_tags_alter_tag_title_alter_topic_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="title",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(2)],
            ),
        ),
    ]
