# Generated by Django 5.1 on 2024-12-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
